CREATE TABLE PortfolioDB
(
	ID INT IDENTITY(1,1) NOT NULL,
	ClientID INT,
	[Name] NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_PortfolioDB PRIMARY KEY (ID),
	CONSTRAINT FK_PortfolioDB_CLientID
				FOREIGN KEY (ClientID) REFERENCES ClientDB (ID)
)