CREATE TABLE PortfolioDB
(
	ID INT IDENTITY(1,1) NOT NULL,
	PortfolioID INT,
	[Name] NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_PortfolioDB PRIMARY KEY (ID),
	CONSTRAINT FK_CLientID
				FOREIGN KEY (PortfolioID) REFERENCES ClientDB (ID)
)