//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountDB()
        {
            this.ClientDBs = new HashSet<ClientDB>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HomeAddressID { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string AspNetUserID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDB> ClientDBs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
