//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LARC_DBEntities : DbContext
    {
        public LARC_DBEntities()
            : base("name=LARC_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountDB> AccountDBs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ClientDB> ClientDBs { get; set; }
        public virtual DbSet<Equity> Equities { get; set; }
        public virtual DbSet<FundEquity> FundEquities { get; set; }
        public virtual DbSet<Fund> Funds { get; set; }
        public virtual DbSet<PortfolioDB> PortfolioDBs { get; set; }
        public virtual DbSet<PortfolioFund> PortfolioFunds { get; set; }
    }
}
