//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PortfolioDB()
        {
            this.PortfolioFunds = new HashSet<PortfolioFund>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Name { get; set; }
    
        public virtual ClientDB ClientDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortfolioFund> PortfolioFunds { get; set; }
    }
}
