//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LARC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioFund
    {
        public int PortfolioID { get; set; }
        public string FundSymbol { get; set; }
        public Nullable<decimal> NumberOfShares { get; set; }
    
        public virtual Fund Fund { get; set; }
        public virtual PortfolioDB PortfolioDB { get; set; }
    }
}
